<?php
/**
 * Created by PhpStorm.
 * User: zhiya
 * Date: 9/19/2019
 * Time: 1:53 PM
 */

namespace JoyBusinessAcademy\Profile\Tests;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Artisan;
use JoyBusinessAcademy\Profile\ProfileServiceProvider;
use Orchestra\Testbench\TestCase AS Base;


class TestCase extends Base
{
    use RefreshDatabase;
    /**
     * Get package providers.
     *
     * @param \Illuminate\Foundation\Application $app
     * @return array
     */
    protected function getPackageProviders($app)
    {
        return [
            ProfileServiceProvider::class
        ];
    }

    /**
     * Setup the test environment.
     *
     * @return void
     */
    protected function setUp(): void
    {
        parent::setUp();

        $this->prepareForTests();
    }

    private function prepareForTests()
    {
        //Artisan::call('migrate');
        //include(__DIR__ . '/../database/seeds/RegionSeeder.php');
        //include(__DIR__ . '/../database/seeds/DatabaseSeeder.php');
        //Artisan::call('db:seed');

        $this->withFactories(__DIR__ . '/../database/factories');
    }

    protected function getEnvironmentSetUp($app)
    {
        parent::getEnvironmentSetUp($app); // TODO: Change the autogenerated stub

        /*$app['config']->set('database.default', 'testDB');
        $app['config']->set('database.connections.testDB', [
            'driver' => 'sqlite',
            'database' => ':memory:'
        ]);*/

        $app['config']->set('jba-profile', include __DIR__ . '/../config/jba-profile.php');

    }

}